project:
  type: book

book:
  title: "Latent Variable Modelling Workflow Reference"
  author: "Alex Rand"
  date: "10/25/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - cfa.qmd
    - sem.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



