project:
  type: book

book:
  title: "Latent Variable Modelling Workflow Reference"
  author: "Alex Rand"
  date: "10/25/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - traditional-cfa-workflow.qmd
    - modification-indexes.qmd
    - mtmm-and-error-structure-modelling.qmd
    - measurement-invariance-testing.qmd
bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



