# Preface {.unnumbered}

## What is this?

This is a book full of code to use when you want to do latent variable modelling. It gives suggested workflows I've cobbled together from a few different textbooks, and has worked examples with data from those textbooks or from open datasets I found online. When you need to do latent variable modelling for your research, you can use these workflows as a place to start. 

Specifically, it seems like these are the sub-areas of latent variable modelling to know how to do:

-   Exploratory Factor Analysis;

-   Confirmatory Factor Analysis;

-   Item Response Theory;

-   Full SEM;

-   Longitudinal SEM.

Maybe I'll discover some other types of things along the way. It's a lifelong journey haha.

## What am I referencing?

The first book on latent variable modelling I read was @gorsuch1983. This was a nice conceptual introduction, but the applied examples were pretty whack. I've since found a few sources with data and R code to work with. I also cite these sources throughout as I cobble together the workflows.

- [_Latent Variable Modelling with R_](https://www.routledge.com/Latent-Variable-Modeling-with-R/Finch-French/p/book/9780415832458), by @Finch2015. They helpfully provide all of the datasets [here](https://www.routledge.com/Latent-Variable-Modeling-with-R/Finch-French/p/book/9780415832458).

- [_Principles and Practice of Structural Equation Modeling_](https://www.guilford.com/books/Principles-and-Practice-of-Structural-Equation-Modeling/Rex-Kline/9781462523344), by @Kline2011. The publisher provides data and code [here](https://www.guilford.com/companion-site/Principles-and-Practice-of-Structural-Equation-Modeling-Fourth-Edition/9781462523344).

- [Confirmatory Factor Analysis for Applied Research](http://www.kharazmi-statistics.ir/Uploads/Public/book/Methodology%20in%20the%20Social%20Sciences.pdf), by @Brown2006. No R code available, but there's some data at [the university website](https://people.bu.edu/tabrown/cfabook.html)

- [Quantitative Analysis Using Structural Equation Modelling](https://www.usgs.gov/centers/wetland-and-aquatic-research-center/science/quantitative-analysis-using-structural-equation), a free online course provided by the Wetland and Aquatic Research Center of the United States Geological Survey.


- [The *lavaan* documentation](https://www.lavaan.ugent.be/tutorial/index.html) has some nice worked examples too.


I'll mostly be using **lavaan** and **tidyverse**, but maybe also some **brms** at some point.

