project:
  type: book
  output-dir: docs

book:
  title: "Latent Variable Modelling Workflow Reference"
  author: "Alex Rand"
  date: "10/25/2022"
  chapters: 
    - index.qmd
    - part: cfa-intro.qmd
      chapters:
        - traditional-cfa-workflow.qmd  
        - modification-indexes.qmd
        - mtmm-and-error-structure-modelling.qmd
        - measurement-invariance-testing.qmd
        - simulating-cfa-data.qmd
        - bayesian-cfa.qmd
    - part: sem-intro.qmd
      chapters:
        - latent-variable-regression.qmd
    
bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



