project:
  type: book
  output-dir: ../docs

book:
  title: "Latent Variable Modelling Workflow Reference"
  author: "Alex Rand"
  date: "10/25/2022"
  chapters: 
    - index.qmd
    - part: cfa-intro.qmd
      chapters:
        - traditional-cfa-workflow.qmd  
        - modification-indexes.qmd
        - mtmm-and-error-structure-modelling.qmd
        - measurement-invariance-testing.qmd
        - regression-with-latent-predictors.qmd
    - part: sem-intro.qmd
    - part: hmm-worked-example.qmd
    
bibliography: references.bib

format:
  html:
    theme: pulse
    code-fold: true
    code-summary: "Code"
    documentclass: scrreprt